# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['sidewalkify', 'sidewalkify.draw', 'sidewalkify.geo', 'sidewalkify.graph']

package_data = \
{'': ['*']}

install_requires = \
['click==7.1.2', 'geopandas==0.3.0', 'networkx>=2.0,<3.0', 'shapely==1.7.1']

setup_kwargs = {
    'name': 'sidewalkify',
    'version': '0.2.1',
    'description': 'Command line tool and Python library for extrapolating sidewalk lines from annotated streets',
    'long_description': None,
    'author': 'Nick Bolten',
    'author_email': 'nbolten@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.6.1,<4.0.0',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
